services:
  mariadb:
    image: mariadb:11
    volumes:
      - "./mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: classicpress
      MYSQL_DATABASE: classicpress
      MYSQL_USER: classicpress
      MYSQL_PASSWORD: classicpress
  classicpress:
    image: ghcr.io/altendorfme/classicpress
    depends_on:
      - mariadb
    volumes:
      - "./classicpress/wp-content:/var/www/wp-content"
    ports:
      - "8123:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: classicpress
      DB_NAME: classicpress
      DB_USER: classicpress
      WP_SITE_URL: http://localhost:8123
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"
